### ISSUE TITLE
Parsing error when query AWS EKS Cluster

### ISSUE THREAD

**Issue by beginga** [pplu/kubernetes-rest#2]
Hello,

I want to use this Per library against an AWS EKS Cluster.
I can get connected and using the Version method.

But if I'm using $api->Core->ListPodForAllNamespaces as in the doc example, I get this error message:
Exception with type: UnparseableResponse: Can't parse JSON content
Detail: SSL connection failed for 485bbc66c67615ad0ef34f0208d32c91.sk1.eu-west-1.eks.amazonaws.com: SSL connect attempt failed with unknown error error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

Regards,

Gautier

**Comment by pplu** [comment]
Hi,

  You have to set the appropiate SSL properties for the server in the constructor. (https://metacpan.org/pod/Kubernetes::REST#SYNOPSIS)

   Or `ssl_ca_file` to the appropiate certificate for the EKS cluster (which you should be able to obtain with an EKS DescribeCluster call to the EKS API), or you specify `ssl_verify_server => 0`, which will skip the SSL certificate verification.

   Hope that helps!

**Comment by pplu** [comment]
@beginga : did my suggestion work for you?

**Comment by beginga** [comment]
Hello,

Yes, your suggestion woks fine.
Here my piece of code for any reuse in AWS-EKS.
Notice, you must first have created the .aws config directory for AWS authentication and the .kube for Kubernetes as well as installing the AWS IAM Authenticator.

ref:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
https://github.com/kubernetes-sigs/aws-iam-authenticator

# AWS IAM Authenticator for EKS
my $authenticator_path = "/usr/bin/aws-iam-authenticator" ;
my $authenticator_cmd = from_json(`$authenticator_path token -i eksCluster`) ; # JSON value
my $authenticator_token = $authenticator_cmd->{status}->{token} ;


my $api = Kubernetes::REST->new(
  credentials => {
    username => $eks_user ,
    password => $eks_key_secret ,
    token => $authenticator_token
  },
  server => {
    endpoint => $endpoint ,
        ssl_verify_server => 0
  },
) ;


regards

**Comment by pplu** [comment]
Thanks for the feedback. Note that instead of invoking the `aws-iam-authenticator`, you can use the `https://metacpan.org/pod/Signer::AWSv4::EKS` module to generate the token.
