### ISSUE TITLE
Mapping to kubectl commands

### ISSUE THREAD

**Issue by beginga** [pplu/kubernetes-rest#3]
Hello,

Could you improve the documentation of the library. I'm particulary interested in on to translate these kubectl commands:
kubectl get --raw /metrics
kubectl get deployment -o wide
kubectl get services -o wide
kubectl get nodes -o wide
kubectl get pods -o wide
kubectl top nodes
kubectl top pod
kubectl exec <POD> <CMD>

Regards,

Gautier

**Comment by pplu** [comment]
Hi,

   As far as I know, kubectl is not a fine wrapper around the Kubernetes API. Most commands have logic around them, specially things like `kubectl apply`

   For the "get" commands, in kubectl you specify a "kind" of object. Kubectl seems to map that to a specific API call. For `get services` it should map to `$k8s->Core->ListNamespacedService`. The way I've found this out is looking in the Kubernetes swagger:
```
     "x-kubernetes-action": "list",
     "x-kubernetes-group-version-kind": {
      "group": "",
      "kind": "Service",
      "version": "v1"
     }
```

   This entry is part of the definition of the operationId "listCoreV1NamespacedService", which in this SDK is `$k8s->Core->ListNamespacedService`.

   I havent found a swagger definition for "/metrics". Maybe we could expose in `Kubernetes::REST` a way for the user to call a raw URL.

   I don't know how the kubectl command handles "top" and "exec".

   Hope this helps!

**Comment by beginga** [comment]
Hello,

I understand.
I will so use kubectl with JSON output when available.

bye
